# Generated by Django 5.0.2 on 2024-03-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(),
        ),
    ]
