# Generated by Django 4.2.11 on 2024-03-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_post_is_published_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category_choices",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Science", "Science"),
                    ("Culture", "Culture"),
                    ("Food", "Food"),
                    ("Tech", "Tech"),
                    ("Fashion", "Fashion"),
                ],
                default="General",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
