# Generated by Django 5.0.3 on 2024-03-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_poster_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_choices',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Science', 'Science'), ('Culture', 'Culture'), ('Food', 'Food'), ('Technology', 'Technology'), ('Fashion', 'Fashion')], default='General', max_length=64),
            preserve_default=False,
        ),
    ]
