# Generated by Django 5.0.2 on 2024-03-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_test_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
