# Generated by Django 5.0.3 on 2024-03-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Science', 'Science')], default='General', max_length=30),
            preserve_default=False,
        ),
    ]
