# Generated by Django 5.0.2 on 2024-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Tech', 'Tech'), ('Science', 'Science'), ('Fashoin', 'Fashoin'), ('Food', 'Food'), ('Cluture', 'Cluture')], max_length=64),
        ),
    ]
