# Generated by Django 4.2.11 on 2024-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_post_category_choices_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="images/default.webp", upload_to="images/"),
        ),
    ]
