# Generated by Django 5.0.3 on 2024-03-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Tech', 'Tech'), ('Science', 'Science'), ('Fashion', 'Fashion')], default='General', max_length=64),
            preserve_default=False,
        ),
    ]
