# Generated by Django 4.2.11 on 2024-03-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="images/4614.jpeg.webp", upload_to="images/"
            ),
        ),
    ]
