# Generated by Django 5.0.3 on 2024-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Science', 'Science'), ('Culture', 'Culture'), ('Food', 'Food'), ('Tech', 'Tech'), ('Fashion', 'Fashion')], max_length=30),
        ),
    ]
