# Generated by Django 4.2.11 on 2024-03-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_post_category_choices_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Tech", "Tech"),
                    ("Science", "Science"),
                    ("Fashion", "Fashion"),
                ],
                max_length=30,
            ),
        ),
    ]
