# Generated by Django 4.2.11 on 2024-03-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Tech", "Tech"),
                    ("Science", "Science"),
                    ("Sports", "Sports"),
                    ("Economy", "Economy"),
                ],
                max_length=30,
            ),
        ),
    ]
