# Generated by Django 5.0.2 on 2024-03-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Tech', 'Tech'), ('Science', 'Science'), ('Fashion', 'Fashion')], default='General', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(default='images/blog-pic.avif', upload_to='images/'),
        ),
    ]
