# Generated by Django 5.0.3 on 2024-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Tech', 'Tech'), ('Science', 'Science'), ('Fashion', 'Fashion')], default='General', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=2048),
        ),
    ]
