# Generated by Django 5.0.3 on 2024-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2024)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('category', models.CharField(choices=[('General', 'General'), ('Food', 'Food'), ('Tech', 'Tech')], max_length=64)),
            ],
        ),
    ]
