# Generated by Django 5.0.3 on 2024-03-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogwebsite',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
