# Generated by Django 5.0.3 on 2024-03-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_blogwebsite_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogwebsite',
            name='poster',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
