# Generated by Django 5.0.1 on 2024-03-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category_post_image_post_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(default='images/regular.jpg', upload_to='images/'),
        ),
    ]
