# Generated by Django 5.0.2 on 2024-03-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Tech', 'Tech'), ('Science', 'Science'), ('Fashion', 'Fashion')], default='General', max_length=64),
            preserve_default=False,
        ),
    ]
